export interface AccountsFavoriteManagement {
  name: string;
  account: any;
  IdAccountFavorite?: number;
  identification?: string;
  ibanBank?: string;
  ibanAccount?: string;
  aliasName?: string;
  typeIdentificacionId?: string;
  publicServiceFavoriteName?: string;
  serviceReference?: string;
  publicServiceCategory?: string;
  publicServiceName?: string;
  publicServiceAccessKeyDescription?: string;
  publicServiceId?: number;
  publicServiceEnterpriseId?: number;
  publicServiceProvider?: string;
  publicServiceProviderPrefix?: string;
  accountId?: number;
  publicServiceEnterpriseDescription?: string;
  publicServiceAccessKeyId?: number;
  publicServiceCode?: number;
  publicServiceFavoriteId?: number | string;
  publicServiceAccessKeyType?: number;
  publicServiceEnterpriseCode?: string;
  publicServiceDescription?: string;
  alias?: string;
  id?: number;
  maxAmount?: number;
  periodicityDescription?: string;
  startDate?: string;
  key?: number;
  publicServiceCategoryId?: number;
  publicServiceCategoryName?: string;
  quota?: number;
}
